### ISSUE TITLE
System.Reflection.TargetException: 'Non-static method requires a target.' when setting navigation property to null

### ISSUE THREAD

**Issue by MattOG** [dbroudy/LazyEntityGraph#24]
AutoFixture v4.14.0
LazyEntityGraph v2.3.4

Setup as such:
```
public class Foo
{
    public Guid IdFoo { get; set; }
    public Guid IdBar { get; set; }
    public virtual Bar Bar { get; set; }
}

public class FooConfiguration : IEntityTypeConfiguration<Foo>
{
    public void Configure(EntityTypeBuilder<Foo> builder)
    {
        // Primary Key
        builder.HasKey(t => t.IdFoo);
        builder.Property(t => t.IdFoo).ValueGeneratedOnAdd();

        // Table & Column Mappings
        builder.ToTable("foos", "foo");
        builder.Property(t => t.IdFoo).HasColumnName("id_foo");
        builder.Property(t => t.IdBar).HasColumnName("id_bar");

        // Relationships
        builder.HasOne(t => t.Bar)
            .WithMany(t => t.Foos)
            .HasForeignKey(d => d.IdBar);
    }
}

public class Bar
{
    public Guid IdBar { get; set; }
    public virtual ICollection<Foo> Foos { get; set; }
}

public class BarConfiguration : IEntityTypeConfiguration<Bar>
{
    public void Configure(EntityTypeBuilder<Bar> builder)
    {
        // Primary Key
        builder.HasKey(t => t.IdBar);
        builder.Property(t => t.IdBar).ValueGeneratedOnAdd();

        // Table & Column Mappings
        builder.ToTable("bars", "bar");
        builder.Property(t => t.IdBar).HasColumnName("id_bar");
    }
}
```

Unit Test:
```
[Fact]
public void UnitTest()
{
    var fixture = new Fixture();
    var modelMetaData = ModelMetadataGenerator.LoadFromContext<MyDbContext>(x => new MyDbContext(x));
    var lazyEntityGraphCustomization = new LazyEntityGraphCustomization(modelMetaData);
    fixture.Customize(lazyEntityGraphCustomization);
    fixture.Customize(new IgnoreNonEnumerableVirtualMembersCustomisation());
    fixture.RepeatCount = 0;
    var f = fixture.Create<Foo>();
    f.Bar = null;
}
```

Last line throws: System.Reflection.TargetException: 'Non-static method requires a target.'

Stack Trace
```
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Reflection.PropertyInfo.GetValue(Object obj)
   at LazyEntityGraph.Core.CollectionProperty.Add[T,TValue](T obj, PropertyInfo pi, TValue value)
   at LazyEntityGraph.Core.Constraints.ManyToOnePropertyConstraint`2.Rebind(THost host, TProperty previousValue, TProperty value)
   at LazyEntityGraph.Core.Property`2.Set(TProperty value)
   at LazyEntityGraph.Core.Property`2.LazyEntityGraph.Core.IProperty<THost>.Set(Object value)
   at LazyEntityGraph.Core.VirtualPropertyInterceptor`1.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.FooProxy.set_Bar(Bar value)
   at Company.Project.Services.UnitTests.Commands.PreProcessors.UnitTests.UnitTest() in path/to/file.cs:line 12
```

Any further info required please ask

**Comment by dbroudy** [comment]
@MattOG Thanks for the detailed report and code. An updated release will be coming shortly.
