### ISSUE TITLE
Add support for .Net6.0

### ISSUE THREAD

**Issue by ElectricVampire** [dbroudy/LazyEntityGraph#31]
Although LazyEntityGraph.EntityFrameworkCore is complied against netstandard its compiled against very old versions of EfCore.
When added it against EfCore 6.0.11 we are getting missing method exception for ClrType Property.
See - https://github.com/dotnet/efcore/issues/26701 - This property was removed in EfCore 6.x versions.

Could please compile and publish the packages against newer version of EntityFrameworkCore to add support for .Net6.0

Error:
Method not found: 'System.Type Microsoft.EntityFrameworkCore.Metadata.ITypeBase.get_ClrType()

StackTrace:
   at LazyEntityGraph.EntityFrameworkCore.ModelMetadataGenerator.<>c.<GenerateModelMetadata>b__1_0(IEntityType x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.DistinctIterator`1.ToList()
   at LazyEntityGraph.Core.ModelMetadata..ctor(IEnumerable`1 entityTypes, IEnumerable`1 constraints)
   at LazyEntityGraph.EntityFrameworkCore.ModelMetadataGenerator.GenerateModelMetadata(DbContext ctx)
   at LazyEntityGraph.EntityFrameworkCore.ModelMetadataGenerator.LoadFromContext[TContext](Func`2 createContext)
   at App.Test.Configure.ConfigureFixture(Boolean isConfigureMembers) in AutoFixtureData.cs:line 78

**Comment by dbroudy** [comment]
I've added a target that compiles against .NET 6 & EF Core 6, and pushed a pre-release version to NuGet. Have a look and let me know if that solves this issue.

It might be a little bit until I can release a new version as the tests for .NET Framework seem to have gotten lost in the version upgrades of other things, and I don't have a .NET Framework environment locally anymore to track the issue down.

**Comment by ElectricVampire** [comment]
@dbroudy Apologies for delayed response. I missed the notification.
Pre release version solved the issue. Will monitor the thread for new release version.

**Comment by dbroudy** [comment]
Fixed in #32
